#!/usr/bin/env python3
"""Render the app privacy policy to the URL the app stores were given.

    scripts/build_privacy.py           write client-prod/privacy.html
    scripts/build_privacy.py --check   fail if the published page is stale

Why this is generated rather than hand-written
----------------------------------------------
The policy has one source of truth, apps/astro/static/privacy.md, which the
astrology API also serves at /astro/privacy. The published page was written
out by hand once, which immediately created the thing it warned about in its
own comment: two copies of a legal document to keep in step, and no way to
notice when they stopped matching. A privacy policy that disagrees with
itself depending on which URL you open is a worse problem than an ugly one.

So the markdown is the document and this renders it. --check compares the
published page against a fresh render and fails if they differ, which is what
CI runs, so drift is caught rather than discovered.

Why a static file and not a route in the single-page app
--------------------------------------------------------
It was a route in the app, and the app has no such route, so /privacy served
the shell: a navbar over nothing, answering HTTP 200 like every other path.
It stayed that way for months. A static file cannot fail that way - it does
not need the bundle to load, JavaScript to run, or the API to be up. The
audience for this URL is an app-store reviewer and, in the worst case, a
regulator; it should have the fewest possible moving parts.
"""
from __future__ import annotations

import argparse
import html
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SOURCE = os.path.join(ROOT, "apps", "astro", "static", "privacy.md")
OUTPUT = os.path.join(ROOT, "client-prod", "privacy.html")

# The markdown signs off with the company name punctuated correctly and
# introduces it with a stray full stop. Normalising the typo is the only
# change made to the text, and it is spelled out here rather than done
# silently, because everything else in this document is reproduced verbatim.
TEXT_FIXES = [("Fleming Analytic Resources. Inc", "Fleming Analytic Resources, Inc.")]

STYLE = """
  :root {
    --ink:#1a1a1a; --ink-2:#444c55; --ink-3:#6b7480;
    --ground:#fff; --surface:#f7f7f5; --rule:#e2e2dd; --accent:#16324f;
    --serif: Georgia, "Times New Roman", serif;
    --sans: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif;
  }
  @media (prefers-color-scheme: dark) {
    :root:not([data-theme="light"]) {
      --ink:#e9edf1; --ink-2:#b3bec9; --ink-3:#8593a1;
      --ground:#12181e; --surface:#182028; --rule:#2a3540; --accent:#8ab4dd;
    }
  }
  * { box-sizing: border-box; }
  body { margin:0; background:var(--ground); color:var(--ink); font-family:var(--sans);
         font-size:17px; line-height:1.65; -webkit-text-size-adjust:100%; }
  .wrap { max-width:46rem; margin:0 auto; padding:3.5rem 1.4rem 5rem; }
  .eyebrow { font-size:.72rem; letter-spacing:.16em; text-transform:uppercase;
             color:var(--ink-3); margin:0 0 .7rem; }
  h1 { font-family:var(--serif); font-weight:600; font-size:clamp(1.9rem,5vw,2.6rem);
       line-height:1.12; margin:0 0 .5rem; text-wrap:balance; }
  .updated { font-size:.9rem; color:var(--ink-3); margin:0 0 2.2rem;
             padding-bottom:1.6rem; border-bottom:2px solid var(--rule); }
  h2 { font-family:var(--serif); font-weight:600; font-size:1.32rem;
       margin:2.6rem 0 .6rem; text-wrap:balance; }
  h3 { font-size:1rem; font-weight:650; margin:1.7rem 0 .4rem; }
  p { margin:0 0 1rem; }
  ul { margin:0 0 1.15rem; padding-left:1.3rem; }
  li { margin-bottom:.5rem; }
  a { color:var(--accent); text-underline-offset:3px; word-break:break-word; }
  a:focus-visible { outline:2px solid var(--accent); outline-offset:3px; border-radius:2px; }
  strong { font-weight:650; }
  hr { border:0; border-top:1px solid var(--rule); margin:3rem 0 1.4rem; }
  hr ~ p { font-size:.88rem; color:var(--ink-3); }
  @media print {
    body { background:#fff; color:#000; font-size:11pt; }
    .wrap { max-width:none; padding:0; }
    a { color:#000; text-decoration:underline; }
  }
"""

PAGE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{title} — Fleming Analytic Resources, Inc.</title>
<meta name="description" content="Privacy policy for the Astrology Chart Generator mobile application by Fleming Analytic Resources, Inc.">
<meta name="robots" content="index, follow">
<link rel="canonical" href="https://fleminganalytic.com/privacy">
<!-- GENERATED by scripts/build_privacy.py from apps/astro/static/privacy.md.
     Do not edit this file: edit the markdown and re-run the script, or the
     two copies of the policy will disagree. CI runs --check to enforce it. -->
<style>{style}</style>
</head>
<body>
<main class="wrap">
<p class="eyebrow">Legal</p>
<h1>{title}</h1>
<p class="updated">{updated}</p>
{body}
</main>
</body>
</html>
"""


def inline(text: str) -> str:
    """Escape, then re-introduce the inline markup the document actually uses."""
    out = html.escape(text, quote=False)
    out = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", out)
    out = re.sub(r"(?<![\">=])\bhttps?://[^\s<)]+", lambda m: f'<a href="{m.group(0)}">{m.group(0)}</a>', out)
    out = re.sub(r"\b([\w.+-]+@[\w-]+\.[\w.]+)\b", r'<a href="mailto:\1">\1</a>', out)
    return out


def render(md: str) -> str:
    """Markdown to HTML, for the subset this document uses.

    A general-purpose converter would pull in a dependency and more behaviour
    than a legal page needs. This handles headings, bullets, bold, links,
    horizontal rules and paragraphs, and raises on anything it does not
    recognise rather than dropping it - silently losing a clause is the one
    failure this must not have.
    """
    out, buf, in_list = [], [], False

    def flush_para():
        if buf:
            out.append(f"<p>{inline(' '.join(buf))}</p>")
            buf.clear()

    def close_list():
        nonlocal in_list
        if in_list:
            out.append("</ul>")
            in_list = False

    for raw in md.split("\n"):
        line = raw.rstrip()
        stripped = line.strip()
        if not stripped:
            flush_para(); close_list(); continue
        if stripped.startswith("#"):
            flush_para(); close_list()
            level = len(stripped) - len(stripped.lstrip("#"))
            if level > 3:
                raise ValueError(f"heading deeper than h3, unhandled: {stripped!r}")
            out.append(f"<h{level}>{inline(stripped.lstrip('#').strip())}</h{level}>")
        elif stripped.startswith("- "):
            flush_para()
            if not in_list:
                out.append("<ul>"); in_list = True
            out.append(f"<li>{inline(stripped[2:].strip())}</li>")
        elif set(stripped) == {"-"} and len(stripped) >= 3:
            flush_para(); close_list()
            out.append("<hr>")
        else:
            close_list()
            buf.append(stripped)
    flush_para(); close_list()
    return "\n".join(out)


def build() -> str:
    with open(SOURCE, encoding="utf-8") as fh:
        md = fh.read()
    for wrong, right in TEXT_FIXES:
        md = md.replace(wrong, right)

    lines = md.split("\n")
    title = lines[0].lstrip("#").strip() if lines[0].startswith("#") else "Privacy Policy"

    # Find the masthead date by POSITION, not by searching the whole document
    # for the phrase. Matching on content deleted the "Changes to This Privacy
    # Policy" clause, because that clause quotes the words "Last updated" -
    # a whole section of a legal document disappeared from the published page
    # and the page still looked perfectly well-formed. Only the header lines,
    # before the first section heading, are eligible.
    updated, updated_at = "", None
    for i, line in enumerate(lines[:8]):
        if line.startswith("##"):
            break
        if "last updated" in line.lower():
            updated = re.sub(r"\*\*", "", line).strip()
            updated_at = i
            break
    if not updated:
        raise ValueError("the policy has no 'Last updated' line in its header - "
                         "a store listing needs one")

    # The title and that one dated line are rendered in the header above, so
    # drop exactly those two lines and keep every other line of the document.
    body_md = "\n".join(l for i, l in enumerate(lines) if i not in (0, updated_at))
    return PAGE.format(title=html.escape(title), style=STYLE,
                       updated=html.escape(updated), body=render(body_md))


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="fail if the published page differs from a fresh render")
    args = ap.parse_args()

    page = build()

    if args.check:
        if not os.path.exists(OUTPUT):
            print(f"FAIL {OUTPUT} does not exist - /privacy would serve the app shell")
            return 1
        with open(OUTPUT, encoding="utf-8") as fh:
            live = fh.read()
        if live != page:
            print("FAIL the published privacy policy no longer matches "
                  "apps/astro/static/privacy.md")
            print("     run scripts/build_privacy.py to regenerate it")
            return 1
        print(f"ok   /privacy matches the policy source ({len(page)} bytes)")
        return 0

    os.makedirs(os.path.dirname(OUTPUT), exist_ok=True)
    with open(OUTPUT, "w", encoding="utf-8") as fh:
        fh.write(page)
    print(f"wrote {OUTPUT} ({len(page)} bytes) from {os.path.relpath(SOURCE, ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
