"""One-shot storage for generated charts, so nothing outlives the request.

The problem this replaces
------------------------
Chart SVGs were written into static/images and never removed. By the time this
was noticed there were 1,040 of them, 244 MB, going back eight months, each
titled with the subject's name - and a natal chart is not an abstraction of
the birth data, it encodes the birth instant and place to arc-minute
precision. Meanwhile the privacy policy said birth data was not retained. The
policy was not lying on purpose; nobody had checked.

Two things kept it invisible. Nothing in the code deleted anything, so there
was no cleanup to notice was broken; and nginx served the files directly from
the static alias, so the application never saw the fetch and had no natural
moment at which to clean up.

How it works now
----------------
Charts are written here, to a directory outside the nginx static alias. That
is the important half: while the files sat under static/, any URL pointing at
them was served by nginx without the application being involved, so no
application-level deletion could be relied on - the old URL would simply keep
working and bypass it.

They are now fetched through the application, which sends the bytes and then
deletes the file. A chart is delivered exactly once.

`sweep()` is the backstop, and it is not optional: a chart that is generated
and never fetched - the visitor closes the tab, the request times out - would
otherwise sit here forever and rebuild the same 244 MB. Every generation
sweeps anything older than MAX_AGE first, so the directory is self-limiting
even if nobody ever collects anything.
"""
from __future__ import annotations

import logging
import os
import re
import time
from pathlib import Path
from typing import Optional

logger = logging.getLogger(__name__)

# Outside static/, deliberately. See the module docstring.
DIR = Path(__file__).resolve().parent.parent.parent / "db" / "astro_transient"

# How long an unfetched artefact may sit here. Long enough that a slow client
# still collects its chart, short enough that abandoned ones do not pile up.
MAX_AGE_SECONDS = 30 * 60

# Filenames are generated by us, but they arrive back from the network in a
# URL, so they are validated rather than trusted. Without this, a request for
# "../../main.py" would read and then DELETE an arbitrary file.
SAFE_NAME = re.compile(r"^[A-Za-z0-9_.-]{1,120}$")


def ensure_dir() -> Path:
    DIR.mkdir(parents=True, exist_ok=True)
    return DIR


def path_for(filename: str) -> Optional[Path]:
    """Resolve a filename to a path inside DIR, or None if it is not one."""
    if not SAFE_NAME.match(filename) or filename in (".", ".."):
        return None
    candidate = (DIR / filename).resolve()
    try:
        # Belt and braces: even with the pattern above, confirm the resolved
        # path really is inside the directory before anything is deleted.
        candidate.relative_to(DIR.resolve())
    except ValueError:
        return None
    return candidate


def take(filename: str) -> Optional[bytes]:
    """Read an artefact and delete it. Returns None if it is not there.

    Read-then-delete, in that order: if the delete failed and we had already
    discarded the bytes, the caller would have nothing to send. The sweep
    catches anything the delete misses.
    """
    path = path_for(filename)
    if path is None or not path.is_file():
        return None
    try:
        data = path.read_bytes()
    except OSError as exc:
        logger.warning(f"astro: could not read transient {filename}: {exc}")
        return None
    try:
        path.unlink()
    except OSError as exc:
        logger.warning(f"astro: served {filename} but could not delete it: {exc}")
    return data


def sweep(max_age_seconds: float = MAX_AGE_SECONDS) -> int:
    """Delete artefacts nobody collected. Returns how many went."""
    if not DIR.exists():
        return 0
    cutoff = time.time() - max_age_seconds
    removed = 0
    for entry in DIR.iterdir():
        try:
            if entry.is_file() and entry.stat().st_mtime < cutoff:
                entry.unlink()
                removed += 1
        except OSError:
            pass
    if removed:
        logger.info(f"astro: swept {removed} uncollected chart artefact(s)")
    return removed


def stats() -> dict:
    if not DIR.exists():
        return {"files": 0, "bytes": 0}
    files = [f for f in DIR.iterdir() if f.is_file()]
    return {"files": len(files), "bytes": sum(f.stat().st_size for f in files)}
